### ISSUE TITLE
Rename repo name to `documentation`

### ISSUE THREAD

**Issue by wuminzhe** [darwinia-network/docs#11]
> The repository specifically created for software documentation on GitHub should be called "docs" or "documentation". These names clearly indicate that the repository is intended to store documentation related to the software. For example, you could create a repository named "docs" and store user manuals, API documentation, installation guides, etc., within it. 
                                                                ------ chatgpt

**Comment by boundless-forest** [comment]
Make sense. Let's give it a lower priority tag, we need to find out where the repo is used before renaming it to avoid 404 errors everywhere.
