### ISSUE TITLE
How to get RING and CRAB tokens.

### ISSUE THREAD

**Issue by hujw77** [darwinia-network/docs#24]
> Also do you have any information on how we can get RING tokens on Darwinia and Crab? I can't find any documentation on onramps for those networks on your website
-- by Ryan Pate from Sphinx.

**Comment by hujw77** [comment]
https://docs.darwinia.network/evm/faq/?h=ring

**Comment by hackfisher** [comment]
https://darwinia.network/#/get-ring

@hujw77 For Integration we can also send some token directly, please leave the address

**Comment by boundless-forest** [comment]
The Q & A  in the FAQ can be improved.
